name: Tests

on:
  push:
    branches: [ main, feat/* ]
  pull_request:
    branches: [ main, feat/* ]

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ ubuntu-latest ]
        node-version: [10.x]
        yarn: [1.22.22]
    runs-on: ${{ matrix.runs-on }}
    name: Tests
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn test
